### ISSUE TITLE
Problems with visualizing results

### ISSUE THREAD

**Issue by jayis520** [craigleili/SRFeat#2]
Hello, I performed a color rendering of the code results and found that the results were not very good, and all the results had such spots.
![1679983497189](https://user-images.githubusercontent.com/48241137/228143630-e0f2ba36-a27d-4f6c-8eef-1935d3576ad8.png)
I use matlab to write visual code, the code is as follows
`close all; clear all;
 M = load_off('D:\wuy\doc\code\SRFeat\exp\data\SHREC_r\shapes\12.off');
 M.surface = construct_surface(M);
 N = load_off('D:\wuy\doc\code\SRFeat\exp\data\SHREC_r\shapes\1.off');
 N.surface = construct_surface(N);
load('D:\wuy\doc\code\SRFeat\exp\log\SRFeat-D_dfn_faust_scape\test_shrec19_22-04-15_22-34-40_eval\1-12.mat');
figure;
visualize_map_on_source(N);
title('Model');
figure;
visualize_map_on_target(M, N, matches);
title('Target');`

**Comment by craigleili** [comment]
Hello,

Here is a visualization I did for the example pair you mentioned, which looks reasonable.

<img width="599" alt="Screenshot 2023-04-02 at 20 49 45" src="https://user-images.githubusercontent.com/15612667/229372896-9d327695-99df-4313-9417-ee79e92235b1.png">

Can you please double-check the visualization code? Note `matches` in `*.mat` files are zero-based.

**Comment by jayis520** [comment]
> Hello,
> 
> Here is a visualization I did for the example pair you mentioned, which looks reasonable.
> 
> <img alt="Screenshot 2023-04-02 at 20 49 45" width="599" src="https://user-images.githubusercontent.com/15612667/229372896-9d327695-99df-4313-9417-ee79e92235b1.png">
> 
> Can you please double-check the visualization code? Note `matches` in `*.mat` files are zero-based.

Can you provide your  visualization code? I will try again using your code
